/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizz;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import quizz.model.Answer;
import quizz.model.Question;
import quizz.model.Quizz;
import quizz.model.QuizzManager;
import quizz.model.Score;
import quizz.model.User;

/**
 *
 * @author Gautier
 */
public class AdminScreenView extends BrainStormingView {

    int m_numberOfLines = 0;
    /**
     * Creates new form AdminScreenView
     */
    public AdminScreenView(MainFrame main) {
        super(main);
        initComponents();
        ArrayList<Quizz> quizzList = Quizz.getQuizzForUser(User.getUserByPseudo(Main.userPseudo).getIdUser());
        for (Quizz quizz : quizzList) {
            this.createQuizzLine(quizz);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton1 = new javax.swing.JButton();
        themeIcon1 = new javax.swing.JLabel();
        themeName1 = new javax.swing.JLabel();
        centralSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton1.setText("Retour");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1backAction(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        themeIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/admin-40.png"))); // NOI18N
        themeIcon1.setMaximumSize(new java.awt.Dimension(80, 80));
        themeIcon1.setMinimumSize(new java.awt.Dimension(80, 80));
        add(themeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 33, -1, -1));

        themeName1.setFont(quizz.Main.s_openSansTitle);
        themeName1.setText("Quizz crées par " + Main.userPseudo);
        add(themeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        centralSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(centralSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 125, -1, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void createQuizzLine(Quizz quizzItem) {
      
        final int lineWidth = 300;
        final Quizz quizz = quizzItem; // Necessary to swap views.
        if (m_numberOfLines < 18) {
            String[] starsIconTitle = new String[3];

            JPanel line = new javax.swing.JPanel();
            JPanel starsPanel = new javax.swing.JPanel();
            JLabel star1 = new javax.swing.JLabel();
            JLabel star2 = new javax.swing.JLabel();
            JLabel star3 = new javax.swing.JLabel();
            JLabel delete = new javax.swing.JLabel();
            JLabel quizzLabel = new javax.swing.JLabel();

            starsPanel.setBackground(new java.awt.Color(255, 255, 255));
            starsPanel.setForeground(new java.awt.Color(255, 255, 255));
            starsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            line.setBackground(new java.awt.Color(255, 255, 255));
            line.setForeground(new java.awt.Color(255, 255, 255));
            line.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            switch (quizz.getDifficulty()) {
                case 2:
                    starsIconTitle[0] = Constants.STAR_FULL;
                    starsIconTitle[1] = Constants.STAR_FULL;
                    starsIconTitle[2] = Constants.STAR_EMPTY;
                    break;
                case 3:
                    starsIconTitle[0] = Constants.STAR_FULL;
                    starsIconTitle[1] = Constants.STAR_FULL;
                    starsIconTitle[2] = Constants.STAR_FULL;
                    break;
                default:
                    starsIconTitle[0] = Constants.STAR_FULL;
                    starsIconTitle[1] = Constants.STAR_EMPTY;
                    starsIconTitle[2] = Constants.STAR_EMPTY;
                    break;
            }

            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Constants.IMAGE_FOLDER + starsIconTitle[0])));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource(Constants.IMAGE_FOLDER + starsIconTitle[1])));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource(Constants.IMAGE_FOLDER + starsIconTitle[2])));
            delete.setIcon(new javax.swing.ImageIcon(getClass().getResource(Constants.IMAGE_FOLDER + Constants.DELETE)));

            starsPanel.add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
            starsPanel.add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));
            starsPanel.add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));
            starsPanel.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

            line.add(starsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            quizzLabel.setText(quizz.getName() + " [" + quizz.getNbQuest() + "Q]");
            line.add(quizzLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, lineWidth, 20));
            line.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    m_mainFrame.setQuizz(quizz);
                    m_mainFrame.changeView(MainFrame.View.QuizzDetailsView);
                }
            });
            
            delete.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    System.out.println("coucou");
                }
            });
            this.setVisible(true);
            this.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(m_numberOfLines > 8 ? 500 : 110, 130 + ((m_numberOfLines > 8 ? m_numberOfLines - 9 : m_numberOfLines) * 40), lineWidth, 20));
            m_numberOfLines++;
        }
    }
    
    private void backButton1backAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1backAction
        m_mainFrame.changeView(MainFrame.View.MainScreenView);
    }//GEN-LAST:event_backButton1backAction

    public void deleteAQuizz(Quizz quizz){
        ArrayList<ArrayList<Answer>> answerListFinal = new ArrayList<ArrayList<Answer>>();
        ArrayList<Question> questions = Question.getQuestionsForQuizz(quizz.getId());
        for(int i=0 ; i<questions.size(); i++){
            answerListFinal.add(Answer.getAnswerForQuestion(questions.get(i).getId()));
        }
        for(int i=0;i<questions.size();i++){
                QuizzManager.deleteLinkAnswerToQuestion(questions.get(i),answerListFinal.get(i));
                QuizzManager.deleteLinkQuestionToQuizz(quizz, questions);
        }
        quizz.deleteQuizzInDB();
        Score.deleteScoreForAQuizz(quizz.getId());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JSeparator centralSeparator1;
    private javax.swing.JLabel themeIcon1;
    private javax.swing.JLabel themeName1;
    // End of variables declaration//GEN-END:variables
}
