/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quizz;

/**
 *
 * @author Gautier
 */
public class CreateQuestionView extends BrainStormingView {

    /**
     * Creates new form CreateQuestionView
     */
    public CreateQuestionView(MainFrame mainFrame) {
        super(mainFrame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        questionNumerLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        leftTextButton = new javax.swing.JButton();
        leftImageButton = new javax.swing.JButton();
        leftBothButton = new javax.swing.JButton();
        arrowLeft = new javax.swing.JLabel();
        arrowRight = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rightTextButton = new javax.swing.JButton();
        rightImageButton = new javax.swing.JButton();
        rightBothButton = new javax.swing.JButton();
        rightPanel = new AnswerPanel(true);
        leftPanel = new AnswerPanel(false);

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(Main.s_openSansTitle);
        titleLabel.setForeground(new java.awt.Color(40, 40, 40));
        titleLabel.setText("Créer une Question");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 0, -1, -1));

        userLabel.setFont(quizz.Main.s_openSans13);
        userLabel.setForeground(new java.awt.Color(102, 102, 102));
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/userIcon-20.png"))); // NOI18N
        userLabel.setText("User");
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });
        add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 6, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 38, 720, -1));

        questionNumerLabel.setFont(Main.s_openSansItalic16);
        questionNumerLabel.setText("Question N°0");
        add(questionNumerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        backButton.setText("Retour");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonbackAction(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        leftTextButton.setBackground(new java.awt.Color(249, 249, 249));
        leftTextButton.setFont(Main.s_openSans13);
        leftTextButton.setLabel("Texte");
        leftTextButton.setMaximumSize(new java.awt.Dimension(90, 35));
        leftTextButton.setMinimumSize(new java.awt.Dimension(90, 35));
        leftTextButton.setPreferredSize(new java.awt.Dimension(90, 35));
        add(leftTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        leftImageButton.setBackground(new java.awt.Color(249, 249, 249));
        leftImageButton.setFont(Main.s_openSans13);
        leftImageButton.setLabel("Image");
        leftImageButton.setMaximumSize(new java.awt.Dimension(90, 35));
        leftImageButton.setMinimumSize(new java.awt.Dimension(90, 35));
        leftImageButton.setPreferredSize(new java.awt.Dimension(90, 35));
        add(leftImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        leftBothButton.setBackground(new java.awt.Color(249, 249, 249));
        leftBothButton.setFont(Main.s_openSans13);
        leftBothButton.setLabel("Les Deux");
        leftBothButton.setMaximumSize(new java.awt.Dimension(90, 35));
        leftBothButton.setMinimumSize(new java.awt.Dimension(90, 35));
        leftBothButton.setPreferredSize(new java.awt.Dimension(90, 35));
        add(leftBothButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        arrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/arrowLeft-60.png"))); // NOI18N
        arrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowLeftgoToPrevious(evt);
            }
        });
        add(arrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        arrowRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/arrowRight-60.png"))); // NOI18N
        arrowRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowRightgoToNextQuestion(evt);
            }
        });
        add(arrowRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMaximumSize(new java.awt.Dimension(1, 400));
        jSeparator2.setMinimumSize(new java.awt.Dimension(1, 400));
        jSeparator2.setPreferredSize(new java.awt.Dimension(1, 400));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        rightTextButton.setBackground(new java.awt.Color(249, 249, 249));
        rightTextButton.setFont(Main.s_openSans13);
        rightTextButton.setLabel("Texte");
        rightTextButton.setMaximumSize(new java.awt.Dimension(90, 35));
        rightTextButton.setMinimumSize(new java.awt.Dimension(90, 35));
        rightTextButton.setPreferredSize(new java.awt.Dimension(90, 35));
        add(rightTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        rightImageButton.setBackground(new java.awt.Color(249, 249, 249));
        rightImageButton.setFont(Main.s_openSans13);
        rightImageButton.setLabel("Image");
        rightImageButton.setMaximumSize(new java.awt.Dimension(90, 35));
        rightImageButton.setMinimumSize(new java.awt.Dimension(90, 35));
        rightImageButton.setPreferredSize(new java.awt.Dimension(90, 35));
        add(rightImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        rightBothButton.setBackground(new java.awt.Color(249, 249, 249));
        rightBothButton.setFont(Main.s_openSans13);
        rightBothButton.setLabel("Les Deux");
        rightBothButton.setMaximumSize(new java.awt.Dimension(90, 35));
        rightBothButton.setMinimumSize(new java.awt.Dimension(90, 35));
        rightBothButton.setPreferredSize(new java.awt.Dimension(90, 35));
        add(rightBothButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        rightPanel.setForeground(new java.awt.Color(102, 102, 102));
        rightPanel.setMaximumSize(new java.awt.Dimension(309, 257));
        rightPanel.setMinimumSize(new java.awt.Dimension(309, 257));
        rightPanel.setPreferredSize(new java.awt.Dimension(309, 307));
        add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        leftPanel.setMaximumSize(new java.awt.Dimension(309, 307));
        leftPanel.setMinimumSize(new java.awt.Dimension(309, 307));
        leftPanel.setPreferredSize(new java.awt.Dimension(309, 307));
        add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        m_mainFrame.addView(MainFrame.modalView.LoginView);
    }//GEN-LAST:event_userLabelMouseClicked

    private void backButtonbackAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonbackAction
        m_mainFrame.changeView(MainFrame.View.CreateQuizzView);
    }//GEN-LAST:event_backButtonbackAction

    private void arrowLeftgoToPrevious(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeftgoToPrevious
        
    }//GEN-LAST:event_arrowLeftgoToPrevious

    private void arrowRightgoToNextQuestion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRightgoToNextQuestion
        
    }//GEN-LAST:event_arrowRightgoToNextQuestion



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrowLeft;
    private javax.swing.JLabel arrowRight;
    private javax.swing.JButton backButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton leftBothButton;
    private javax.swing.JButton leftImageButton;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton leftTextButton;
    private javax.swing.JLabel questionNumerLabel;
    private javax.swing.JButton rightBothButton;
    private javax.swing.JButton rightImageButton;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton rightTextButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
