/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizz;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import quizz.model.Quizz;
import quizz.model.Theme;

/**
 *
 * @author Gautier
 */
public class CreateQuizzView extends BrainStormingView {

    /**
     * Creates new form CreateQuizzPanel
     */
    public CreateQuizzView(MainFrame mainFrame) {
        super(mainFrame);
        initComponents();
        ArrayList<Theme> arrayListTheme = new ArrayList<>();
        arrayListTheme = Theme.getAllThemes();
        String[] themeList = new String[arrayListTheme.size()];
        for (int i = 0; i < arrayListTheme.size(); i++) {
            themeList[i] = arrayListTheme.get(i).getNameTheme();
        }
        folderSelector.setModel(new javax.swing.DefaultComboBoxModel(themeList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        subtitleLabel = new javax.swing.JLabel();
        mainPanel = new RoundedPanel();
        paperIcon = new javax.swing.JLabel();
        flagIcon = new javax.swing.JLabel();
        minuteField = new javax.swing.JTextField();
        difficultySelector = new javax.swing.JComboBox();
        replayableIcon = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        infoLabel = new javax.swing.JLabel();
        folderSelector = new javax.swing.JComboBox();
        hourglassIcon = new javax.swing.JLabel();
        folderIcon = new javax.swing.JLabel();
        replayableCheckbox = new javax.swing.JCheckBox();
        createButton = new javax.swing.JButton();
        starIcon3 = new javax.swing.JLabel();
        starIcon1 = new javax.swing.JLabel();
        starIcon2 = new javax.swing.JLabel();
        secondField = new javax.swing.JTextField();
        minuteLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setVerifyInputWhenFocusTarget(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(Main.s_openSansTitle);
        titleLabel.setForeground(new java.awt.Color(40, 40, 40));
        titleLabel.setText("Créer un Quizz");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 0, -1, -1));
        titleLabel.getAccessibleContext().setAccessibleName("");

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 38, 720, -1));

        subtitleLabel.setFont(Main.s_openSansItalic16);
        subtitleLabel.setForeground(new java.awt.Color(102, 102, 102));
        subtitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/settingIcon-15.png"))); // NOI18N
        subtitleLabel.setText("Paramètres du Quizz");
        add(subtitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 50, -1, -1));
        subtitleLabel.getAccessibleContext().setAccessibleName("subtittleLabel");

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(102, 102, 102));
        mainPanel.setMaximumSize(new java.awt.Dimension(500, 300));
        mainPanel.setMinimumSize(new java.awt.Dimension(500, 300));
        mainPanel.setPreferredSize(new java.awt.Dimension(500, 300));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paperIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paperIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/paperIcon-25.png"))); // NOI18N
        paperIcon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        paperIcon.setAlignmentX(0.5F);
        mainPanel.add(paperIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        flagIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/flagIcon-25.png"))); // NOI18N
        mainPanel.add(flagIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        minuteField.setFont(Main.s_openSans13);
        minuteField.setForeground(new java.awt.Color(102, 102, 102));
        minuteField.setMaximumSize(new java.awt.Dimension(150, 24));
        minuteField.setMinimumSize(new java.awt.Dimension(150, 24));
        minuteField.setPreferredSize(new java.awt.Dimension(150, 24));
        minuteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minuteFieldActionPerformed(evt);
            }
        });
        mainPanel.add(minuteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 40, 30));

        difficultySelector.setFont(Main.s_openSans13);
        difficultySelector.setForeground(new java.awt.Color(102, 102, 102));
        difficultySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Facile", "Moyen", "Difficile" }));
        difficultySelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                difficultySelectorItemStateChanged(evt);
            }
        });
        mainPanel.add(difficultySelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, -1));

        replayableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/replayableIcon-25.png"))); // NOI18N
        mainPanel.add(replayableIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        nameField.setFont(Main.s_openSans13);
        nameField.setForeground(new java.awt.Color(102, 102, 102));
        nameField.setText("Nom du Quizz");
        nameField.setMaximumSize(new java.awt.Dimension(150, 24));
        nameField.setMinimumSize(new java.awt.Dimension(150, 24));
        nameField.setPreferredSize(new java.awt.Dimension(150, 24));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
        });
        mainPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        infoLabel.setFont(Main.s_openSans13);
        infoLabel.setText("Laisser vide si temps infini");
        mainPanel.add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        folderSelector.setForeground(new java.awt.Color(102, 102, 102));
        folderSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thème 1", "Thème 2", "Thème 3" }));
        folderSelector.setSelectedItem("Thème");
        folderSelector.setMaximumSize(new java.awt.Dimension(59, 20));
        folderSelector.setMinimumSize(new java.awt.Dimension(59, 20));
        folderSelector.setPreferredSize(new java.awt.Dimension(59, 20));
        mainPanel.add(folderSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 150, -1));

        hourglassIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/hourglassIcon-25.png"))); // NOI18N
        mainPanel.add(hourglassIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        folderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/folderIcon-25.png"))); // NOI18N
        mainPanel.add(folderIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        replayableCheckbox.setFont(Main.s_openSans13);
        replayableCheckbox.setForeground(new java.awt.Color(102, 102, 102));
        replayableCheckbox.setText("Rejouable ?");
        mainPanel.add(replayableCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        createButton.setText("Créer");
        createButton.setMaximumSize(new java.awt.Dimension(80, 35));
        createButton.setMinimumSize(new java.awt.Dimension(80, 35));
        createButton.setPreferredSize(new java.awt.Dimension(80, 35));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        mainPanel.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        starIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starEmpty-20.png"))); // NOI18N
        mainPanel.add(starIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        starIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starFull-20.png"))); // NOI18N
        mainPanel.add(starIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        starIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starEmpty-20.png"))); // NOI18N
        mainPanel.add(starIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        secondField.setForeground(new java.awt.Color(102, 102, 102));
        mainPanel.add(secondField, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 150, 40, 30));

        minuteLabel.setForeground(new java.awt.Color(102, 102, 102));
        minuteLabel.setText("Min");
        mainPanel.add(minuteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        secondLabel.setForeground(new java.awt.Color(102, 102, 102));
        secondLabel.setText("Sec");
        mainPanel.add(secondLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 30, -1));

        add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        backButton.setText("Retour");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonbackAction(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        userLabel.setFont(quizz.Main.s_openSans13);
        userLabel.setForeground(new java.awt.Color(102, 102, 102));
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/userIcon-20.png"))); // NOI18N
        userLabel.setText(Main.userPseudo);
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });
        add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 6, -1, -1));

        getAccessibleContext().setAccessibleName("CreateQuizzPanel");
    }// </editor-fold>//GEN-END:initComponents

    private void minuteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minuteFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void backButtonbackAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonbackAction
        m_mainFrame.changeView(MainFrame.View.MainScreenView);
    }//GEN-LAST:event_backButtonbackAction

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    }//GEN-LAST:event_formFocusGained

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if (!nameField.getText().equals("")) {
            int idTheme = Theme.getThemeByName((String) folderSelector.getSelectedItem()).getId();
            int idAdmin = 1; //en attendant que le system de compte soit mis en place
            int dif = 0;
            int time;
            switch ((String) difficultySelector.getSelectedItem()) {
                case "Facile":
                    dif = 1;
                    break;
                case "Moyen":
                    dif = 2;
                    break;
                case "Difficile":
                    dif = 3;
                    break;
            }
            if(minuteField.getText().isEmpty() || minuteField.getText().equals("0")){
               time = 0;
            }else{
                time = Integer.parseInt(minuteField.getText())*60000;
            }
            if(secondField.getText().isEmpty() || minuteField.getText().equals("0")){
                time = time + 0;
            }else {
                time = time + (Integer.parseInt(secondField.getText())*1000);               
            }
            System.out.println("test temps : "+time);
            Quizz newQuizz = new Quizz(idTheme, idAdmin, dif, time, replayableCheckbox.isSelected(), nameField.getText());
            this.m_mainFrame.setQuizz(newQuizz);
            m_mainFrame.changeView(MainFrame.View.CreateQuestionView);
        }

    }//GEN-LAST:event_createButtonActionPerformed

    
    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        m_mainFrame.addView(MainFrame.modalView.LoginView);
    }//GEN-LAST:event_userLabelMouseClicked

    private void difficultySelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_difficultySelectorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED ) {
            if(evt.getItem().equals("Moyen")){
                this.starIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starFull-20.png")));
                this.starIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starFull-20.png")));
                this.starIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starEmpty-20.png")));
            }else if(evt.getItem().equals("Difficile")){
                this.starIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starFull-20.png")));
                this.starIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starFull-20.png")));
                this.starIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starFull-20.png")));
            }else{
                this.starIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starFull-20.png")));
                this.starIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starEmpty-20.png")));
                this.starIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/starEmpty-20.png")));
            }
        }
    }//GEN-LAST:event_difficultySelectorItemStateChanged

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        this.nameField.setText("");
    }//GEN-LAST:event_nameFieldFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox difficultySelector;
    private javax.swing.JLabel flagIcon;
    private javax.swing.JLabel folderIcon;
    private javax.swing.JComboBox folderSelector;
    private javax.swing.JLabel hourglassIcon;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField minuteField;
    private javax.swing.JLabel minuteLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel paperIcon;
    private javax.swing.JCheckBox replayableCheckbox;
    private javax.swing.JLabel replayableIcon;
    private javax.swing.JTextField secondField;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel starIcon1;
    private javax.swing.JLabel starIcon2;
    private javax.swing.JLabel starIcon3;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
