/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quizz;

/**
 *
 * @author Vince
 */
public class MainScreenView extends BrainStormingView {

    public MainScreenView(MainFrame mainFrame) {
        super(mainFrame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScreenTitle = new javax.swing.JLabel();
        createQuizz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainScreenTitle.setFont(quizz.Main.s_openSansTitle);
        mainScreenTitle.setText("Brain Storming");
        mainScreenTitle.setName("mainScreenTitle"); // NOI18N
        add(mainScreenTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        createQuizz.setText("Créer Quizz");
        createQuizz.setActionCommand("createQuizz");
        createQuizz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuizzActionPerformed(evt);
            }
        });
        add(createQuizz, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/linux-100.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                selectTheme(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 350, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/linux-100.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2selectTheme(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 150, 100, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/linux-100.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3selectTheme(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 100, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/linux-100.png"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4selectTheme(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 150, 100, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/linux-100.png"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5selectTheme(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, 100, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/linux-100.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6selectTheme(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 100, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void createQuizzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQuizzActionPerformed
        m_mainFrame.changeView(MainFrame.View.CreateQuizzView);
    }//GEN-LAST:event_createQuizzActionPerformed

    private void selectTheme(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectTheme
        m_mainFrame.changeView(MainFrame.View.QuestionScreenView);
    }//GEN-LAST:event_selectTheme

    private void jLabel2selectTheme(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2selectTheme
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2selectTheme

    private void jLabel3selectTheme(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3selectTheme
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3selectTheme

    private void jLabel4selectTheme(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4selectTheme
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4selectTheme

    private void jLabel5selectTheme(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5selectTheme
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5selectTheme

    private void jLabel6selectTheme(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6selectTheme
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6selectTheme



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createQuizz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mainScreenTitle;
    // End of variables declaration//GEN-END:variables
}
