/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quizz;

import javax.swing.JPasswordField;

/**
 *
 * @author Gautier
 */
public class SignInDialogPanel extends RoundedPanel {

    /**
     * Creates new form SignInDialog
     */
    private MainFrame m_mainFrame;
    SignInDialogPanel(MainFrame mainFrame) {
        initComponents();
        m_mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pseudoTextBox = new javax.swing.JTextField();
        passwordTextBox = new JPasswordField(10);
        userIconLabel = new javax.swing.JLabel();
        padlockIconLabel = new javax.swing.JLabel();
        confirmPasswordTextBpx = new JPasswordField(10);
        passwordTextBox1 = new javax.swing.JTextField();
        padlockIconLabel2 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        messageIconLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(349, 316));
        setMinimumSize(new java.awt.Dimension(349, 316));
        setPreferredSize(new java.awt.Dimension(349, 316));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pseudoTextBox.setFont(Main.s_openSans13);
        pseudoTextBox.setForeground(new java.awt.Color(170, 170, 170));
        pseudoTextBox.setText("Pseudo");
        pseudoTextBox.setToolTipText("");
        pseudoTextBox.setMaximumSize(new java.awt.Dimension(120, 10));
        pseudoTextBox.setMinimumSize(new java.awt.Dimension(120, 5));
        pseudoTextBox.setPreferredSize(new java.awt.Dimension(120, 5));
        pseudoTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudoTextBoxActionPerformed(evt);
            }
        });
        add(pseudoTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 82, 120, 20));

        passwordTextBox.setFont(Main.s_openSans13);
        passwordTextBox.setForeground(new java.awt.Color(170, 170, 170));
        passwordTextBox.setText("jTextField2");
        passwordTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(passwordTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 122, 120, -1));

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/userIcon-25.png"))); // NOI18N
        add(userIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 82, 25, -1));

        padlockIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/padlock-25.png"))); // NOI18N
        add(padlockIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 122, 25, -1));

        confirmPasswordTextBpx.setFont(Main.s_openSans13);
        confirmPasswordTextBpx.setForeground(new java.awt.Color(170, 170, 170));
        confirmPasswordTextBpx.setText("jTextField2");
        confirmPasswordTextBpx.setToolTipText("");
        confirmPasswordTextBpx.setMaximumSize(new java.awt.Dimension(120, 10));
        confirmPasswordTextBpx.setMinimumSize(new java.awt.Dimension(120, 5));
        confirmPasswordTextBpx.setPreferredSize(new java.awt.Dimension(120, 5));
        confirmPasswordTextBpx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordTextBpxActionPerformed(evt);
            }
        });
        add(confirmPasswordTextBpx, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 165, 120, 20));

        passwordTextBox1.setFont(Main.s_openSans13);
        passwordTextBox1.setForeground(new java.awt.Color(170, 170, 170));
        passwordTextBox1.setText("e-mail");
        passwordTextBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextBox1ActionPerformed(evt);
            }
        });
        add(passwordTextBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 205, 120, -1));

        padlockIconLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/padlock-25.png"))); // NOI18N
        add(padlockIconLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 165, 25, -1));

        titleLabel.setFont(Main.s_openSans28);
        titleLabel.setText("Inscription");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 23, -1, -1));

        messageIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/assets/messageIcon-25.png"))); // NOI18N
        add(messageIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 205, 25, -1));

        signInButton.setText("Inscription");
        signInButton.setMaximumSize(new java.awt.Dimension(100, 35));
        signInButton.setMinimumSize(new java.awt.Dimension(100, 35));
        signInButton.setPreferredSize(new java.awt.Dimension(100, 35));
        add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 248, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pseudoTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudoTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudoTextBoxActionPerformed

    private void confirmPasswordTextBpxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordTextBpxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordTextBpxActionPerformed

    private void passwordTextBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmPasswordTextBpx;
    private javax.swing.JLabel messageIconLabel;
    private javax.swing.JLabel padlockIconLabel;
    private javax.swing.JLabel padlockIconLabel2;
    private javax.swing.JTextField passwordTextBox;
    private javax.swing.JTextField passwordTextBox1;
    private javax.swing.JTextField pseudoTextBox;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userIconLabel;
    // End of variables declaration//GEN-END:variables
}
